defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"
      author: "Brent Walther"
      permalink: :title

exclude: [README.md, Gemfile, Gemfile.lock]
